### ISSUE TITLE
没有data目录啊

### ISSUE THREAD

**Issue by lab-gpu** [ming71/SLA#1]
代码里面涉及到的data目录，怎么没有呢

**Comment by lab-gpu** [comment]
![Uploading 微信图片_20210917200758.png…]()

**Comment by lab-gpu** [comment]
![微信图片_20210917200758](https://user-images.githubusercontent.com/70756793/133780378-22c3793f-f85c-483a-9873-6c8116a2bfd5.png)

**Comment by ming71** [comment]
删除数据集的时候把这个也误删了，已重新上传
