### ISSUE TITLE
test.py 卡住了 怎么解决呀  ming  救我！

### ISSUE THREAD

**Issue by yzk-lab** [ming71/SLA#2]
![A9M}Q38F7 9~ YXA3L__8OV](https://user-images.githubusercontent.com/41197028/139248459-ad1f26a1-cea5-4d80-815b-8cb55b33f4c7.png)

**Comment by yzk-lab** [comment]
是因为DOTA数据集没有真实标签 在DOTA文件夹下annotations/test_crop和annotation/test_crop_768文件都为空的缘故吗？望指教。

**Comment by ming71** [comment]
可能不是卡住了，是在正常运行。patch merging的时候用的cpu比较慢，，等一段时间就merge完了
