### ISSUE TITLE
low map on HRSC2016 with default config

### ISSUE THREAD

**Issue by Sharpiless** [ming71/SLA#3]
100%|████████████████████████████████████████████████████████████████████████████████| 57/57 [01:18<00:00,  1.38s/it]
AP
ship: 29.489750676913513
mAP: 29.489750676913513

**Comment by ming71** [comment]
Sorry to see your message so late. 
Did you modify the training parameters (lr, epochs, size, etc), or use the mismatched sizes for testing?
