### ISSUE TITLE
论文的图

### ISSUE THREAD

**Issue by shenhaibb** [ming71/SLA#4]
想问一下大佬您这张图中的网格线 是用代码生成的还是手动绘制的呢 如果是代码生成的代码中在哪体现呢
求指点！！万分感谢！！
![demo](https://user-images.githubusercontent.com/64736467/156289113-a9ad61f0-8021-4eba-84db-27f129e19b72.png)

**Comment by ming71** [comment]
这个是示意图,网格线不是代码生成的.
anchor位置信息可以生成,在输出detection时额外加上对应的初始anchor信息,同时画在图上就行.

**Comment by shenhaibb** [comment]
> 

好的！十分感谢大佬的回复
